# Generated by Django 5.1.4 on 2024-12-31 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='legend',
            name='slug',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weapon',
            name='slug',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
    ]
