# Generated by Django 5.1.2 on 2024-10-27 04:54

import django.db.models.deletion
import main.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Legend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='user',
            name='codex_coins',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='discord_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.CreateModel(
            name='LegendWeaponPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pairs', to='main.legend')),
                ('weapon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pairs', to='main.weapon')),
            ],
        ),
        migrations.CreateModel(
            name='DailyChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('legends_weapons', models.ManyToManyField(related_name='daily_challenges', to='main.legendweaponpair')),
            ],
        ),
        migrations.CreateModel(
            name='Combo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_verified', models.BooleanField(default=False, editable=False)),
                ('upload_date', models.DateField(auto_now_add=True)),
                ('outdated', models.BooleanField(default=False)),
                ('map_specific', models.BooleanField(default=False)),
                ('video', models.FileField(upload_to=main.models.upload_to_combo)),
                ('users', models.ManyToManyField(blank=True, related_name='combos', to=settings.AUTH_USER_MODEL)),
                ('challenge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='combos', to='main.dailychallenge')),
                ('guests', models.ManyToManyField(blank=True, related_name='combos', to='main.guest')),
                ('legends_weapons', models.ManyToManyField(related_name='combos', to='main.legendweaponpair')),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('combo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='main.combo')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to=settings.AUTH_USER_MODEL)),
                ('weapons_legends', models.ManyToManyField(related_name='requests', to='main.legendweaponpair')),
            ],
        ),
        migrations.AddField(
            model_name='legend',
            name='weapons',
            field=models.ManyToManyField(related_name='legends', to='main.weapon'),
        ),
        migrations.AddConstraint(
            model_name='legendweaponpair',
            constraint=models.UniqueConstraint(fields=('legend', 'weapon'), name='legend_weapon_unique'),
        ),
    ]
