# Generated by Django 5.1.2 on 2024-10-27 04:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_guest_legend_weapon_user_codex_coins_user_discord_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='combo',
            options={'ordering': ['upload_date', 'outdated']},
        ),
        migrations.AlterField(
            model_name='request',
            name='combo',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.combo'),
        ),
    ]
