# Generated by Django 5.1.4 on 2024-12-31 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_legend_slug_weapon_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legend',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
