# Generated by Django 5.1.3 on 2024-11-09 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_combo_options_alter_request_combo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('link', models.URLField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
