# Generated by Django 5.1.4 on 2024-12-31 18:07

import django.db.models.deletion
import main.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_guest_alter_legend_slug_alter_weapon_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Combo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_verified', models.BooleanField(default=False)),
                ('is_outdated', models.BooleanField(default=False)),
                ('is_map_specific', models.BooleanField(default=False)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('video', models.FileField(upload_to=main.models.combo_video_upload_to)),
                ('guests', models.ManyToManyField(blank=True, related_name='combos', to='main.guest')),
                ('legend_one', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combos_one', to='main.legend')),
                ('legend_two', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combos_two', to='main.legend')),
                ('users', models.ManyToManyField(blank=True, related_name='combos', to=settings.AUTH_USER_MODEL)),
                ('weapon_one', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combos_one', to='main.weapon')),
                ('weapon_two', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combos_two', to='main.weapon')),
            ],
            options={
                'ordering': ['is_outdated', '-created_on'],
            },
        ),
    ]
