# Generated by Django 5.1.4 on 2025-01-01 20:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_combo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateField(auto_now_add=True)),
                ('legend_one', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_challenges_one', to='main.legend')),
                ('legend_two', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_challenges_two', to='main.legend')),
                ('weapon_one', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_challenges_one', to='main.weapon')),
                ('weapon_two', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_challenges_two', to='main.weapon')),
            ],
        ),
        migrations.AddField(
            model_name='combo',
            name='daily_challenge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='combos', to='main.dailychallenge'),
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateField(auto_now_add=True)),
                ('combo', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='request', to='main.combo')),
                ('legend_one', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests_one', to='main.legend')),
                ('legend_two', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests_two', to='main.legend')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requests', to=settings.AUTH_USER_MODEL)),
                ('weapon_one', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests_one', to='main.weapon')),
                ('weapon_two', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests_two', to='main.weapon')),
            ],
        ),
    ]
