# Generated by Django 5.1.4 on 2025-01-05 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_dailychallenge_combo_daily_challenge_request'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('slug', models.SlugField(blank=True, editable=False)),
                ('order', models.PositiveIntegerField(unique=True)),
            ],
            options={
                'ordering': ['order'],
                'abstract': False,
            },
        ),
    ]
