# Generated by Django 5.1.4 on 2025-01-05 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_websitesocial'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitesocial',
            name='link',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
