# Generated by Django 5.1.4 on 2025-01-05 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_websitesocial_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='combo',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
