# Generated by Django 5.1.4 on 2025-01-22 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_combo_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
