# Generated by Django 5.1.4 on 2025-01-28 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_request_notes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='combo',
            options={'ordering': ['-id']},
        ),
    ]
