# Generated by Django 5.1.4 on 2025-02-28 21:07

import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_combo_is_alternate_gamemode'),
    ]

    operations = [
        migrations.AddField(
            model_name='combo',
            name='poster',
            field=models.ImageField(blank=True, upload_to=main.models.combo_post_upload_to),
        ),
    ]
