# Generated by Django 5.1.4 on 2025-02-28 21:28

import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_combo_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='combo',
            name='poster',
            field=models.ImageField(upload_to=main.models.combo_post_upload_to),
        ),
    ]
