# Generated by Django 5.1.4 on 2025-03-09 05:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_combo_created_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='combo',
            name='created_on',
            field=models.DateField(default=datetime.datetime.today),
        ),
        migrations.AlterField(
            model_name='dailychallenge',
            name='created_on',
            field=models.DateField(default=datetime.datetime.today),
        ),
        migrations.AlterField(
            model_name='request',
            name='created_on',
            field=models.DateField(default=datetime.datetime.today),
        ),
    ]
