# Generated by Django 5.1.4 on 2025-03-09 07:43

import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_combo_created_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='combo',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to=main.models.combo_post_upload_to),
        ),
    ]
