# Generated by Django 5.1.4 on 2025-03-10 22:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0017_alter_combo_poster"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="combo",
            name="guests",
            field=models.ManyToManyField(
                blank=True, editable=False, related_name="combos", to="main.guest"
            ),
        ),
        migrations.AlterField(
            model_name="combo",
            name="users",
            field=models.ManyToManyField(
                blank=True,
                editable=False,
                related_name="combos",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="request",
            name="combo",
            field=models.OneToOneField(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="request",
                to="main.combo",
            ),
        ),
    ]
