# Generated by Django 5.1.4 on 2025-03-11 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0018_alter_combo_guests_alter_combo_users_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dailychallenge",
            options={"ordering": ["-id"]},
        ),
        migrations.AlterModelOptions(
            name="request",
            options={"ordering": ["-id"]},
        ),
    ]
