# Generated by Django 5.1.4 on 2025-03-12 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0019_alter_dailychallenge_options_alter_request_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="guest",
            name="username",
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
