# Generated by Django 5.1.4 on 2025-03-15 04:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0021_alter_combo_options_combo_is_preferred"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="combo",
            options={"ordering": ["-id"]},
        ),
        migrations.AlterField(
            model_name="combo",
            name="daily_challenge",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="combos",
                to="main.dailychallenge",
            ),
        ),
        migrations.AlterField(
            model_name="combo",
            name="views",
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
