# Generated by Django 5.1.4 on 2025-03-21 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_rename_is_preferred_combo_is_recommended'),
    ]

    operations = [
        migrations.AddField(
            model_name='combo',
            name='video_duration',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
