# Generated by Django 5.1.4 on 2025-04-09 13:02

import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0024_combo_video_duration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="combo",
            name="poster",
            field=models.ImageField(
                blank=True,
                editable=False,
                null=True,
                upload_to=main.models.combo_post_upload_to,
            ),
        ),
        migrations.AlterField(
            model_name="combo",
            name="views",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
