# Generated by Django 5.1.4 on 2025-01-13 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_codex_coins'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_trusted',
            field=models.BooleanField(default=False),
        ),
    ]
