# Generated by Django 5.1.4 on 2025-01-28 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_is_trusted'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('price', models.PositiveSmallIntegerField(default=10)),
                ('slug', models.SlugField(blank=True, editable=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
