# Generated by Django 5.1.4 on 2025-01-29 04:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_usercolor'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='user.usercolor'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_colors',
            field=models.ManyToManyField(blank=True, to='user.usercolor'),
        ),
    ]
