# Generated by Django 5.1.4 on 2025-01-30 02:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_user_user_color_user_user_colors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users_individual', to='user.usercolor'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_colors',
            field=models.ManyToManyField(blank=True, related_name='users', to='user.usercolor'),
        ),
    ]
