# Generated by Django 5.1.4 on 2025-01-31 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_usertheme_user_user_theme_user_user_themes'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertheme',
            name='primary_color',
            field=models.CharField(default='', max_length=7),
            preserve_default=False,
        ),
    ]
