# Generated by Django 5.1.4 on 2025-02-01 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_usertheme_primary_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBackground',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('price', models.PositiveSmallIntegerField(default=10)),
                ('slug', models.SlugField(blank=True, editable=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='user',
            name='user_background',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users_individual', to='user.userbackground'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_backgrounds',
            field=models.ManyToManyField(blank=True, related_name='users', to='user.userbackground'),
        ),
    ]
