# Generated by Django 5.1.4 on 2025-02-01 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_userbackground_user_user_background_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
