# Generated by Django 5.1.4 on 2025-02-25 01:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_alter_user_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.TextField()),
                ('content', models.TextField()),
                ('link', models.URLField(blank=True, null=True)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('read', models.BooleanField(default=False)),
                ('users', models.ManyToManyField(related_name='mail', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
