# Generated by Django 5.1.4 on 2025-02-25 20:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_mail'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mail',
            options={'ordering': ['-created_on']},
        ),
        migrations.AlterField(
            model_name='mail',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='mail', to=settings.AUTH_USER_MODEL),
        ),
    ]
