# Generated by Django 5.1.4 on 2025-02-25 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_alter_mail_options_alter_mail_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail',
            name='link',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
