# Generated by Django 5.1.4 on 2025-02-27 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_alter_mail_link'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mail',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='mail',
            name='type',
            field=models.CharField(choices=[('good', 'Good'), ('bad', 'Bad')], default='good', max_length=8),
        ),
    ]
