# Generated by Django 5.1.4 on 2025-03-04 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_combo_poster'),
        ('user', '0015_alter_mail_options_mail_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favorite_combos',
            field=models.ManyToManyField(blank=True, related_name='favorite_users', to='main.combo'),
        ),
    ]
