# Generated by Django 5.1.4 on 2025-03-04 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_user_favorite_combos'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='discord_id',
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
    ]
