# Generated by Django 5.1.4 on 2025-03-08 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_user_discord_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_theme',
            field=models.CharField(default='#239063', max_length=7),
        ),
    ]
