# Generated by Django 5.1.4 on 2025-03-08 21:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_alter_user_user_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='theme_color',
            field=models.CharField(default='#239063', max_length=7),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users_individual', to='user.usertheme'),
        ),
    ]
